"""Load SuperRobot user environment from ~/.config/superrobot/.env."""

from __future__ import annotations

import os
import re
from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "superrobot"
ENV_FILE = CONFIG_DIR / ".env"
STATE_FILE = CONFIG_DIR / "setup.yaml"

_ENV_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")


def ensure_config_dir() -> Path:
    """Create config directory if missing."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    return CONFIG_DIR


def load_user_env() -> None:
    """Load ~/.config/superrobot/.env into os.environ (setdefault only)."""
    if not ENV_FILE.exists():
        return
    for line in ENV_FILE.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = _ENV_LINE.match(stripped)
        if match:
            key, value = match.group(1), match.group(2).strip().strip('"').strip("'")
            os.environ.setdefault(key, value)


def write_env_file(values: dict[str, str]) -> Path:
    """Write environment variables to user .env file."""
    ensure_config_dir()
    lines = ["# SuperRobot environment — generated by superrobot setup", ""]
    for key, value in values.items():
        lines.append(f"{key}={value}")
    lines.append("")
    ENV_FILE.write_text("\n".join(lines))
    for key, value in values.items():
        os.environ[key] = value
    return ENV_FILE


def read_env_file() -> dict[str, str]:
    """Read current user .env values."""
    if not ENV_FILE.exists():
        return {}
    result: dict[str, str] = {}
    for line in ENV_FILE.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = _ENV_LINE.match(stripped)
        if match:
            result[match.group(1)] = match.group(2).strip().strip('"').strip("'")
    return result
